#!/bin/bash

MOTOR1_DIR_GPIO=61
MOTOR2_DIR_GPIO=32
MOTOR3_DIR_GPIO=33
MOTOR4_DIR_GPIO=36
MOTOR5_DIR_GPIO=37
MOTOR6_DIR_GPIO=62
MOTOR7_DIR_GPIO=65
MOTOR8_DIR_GPIO=63

MOTOR1_SENSE1_GPIO=45
MOTOR1_SENSE2_GPIO=44
MOTOR2_SENSE1_GPIO=69
MOTOR2_SENSE2_GPIO=68
MOTOR3_SENSE1_GPIO=66
MOTOR3_SENSE2_GPIO=67
MOTOR4_SENSE1_GPIO=34
MOTOR4_SENSE2_GPIO=26
MOTOR5_SENSE1_GPIO=38
MOTOR5_SENSE2_GPIO=39
MOTOR6_SENSE1_GPIO=47
MOTOR6_SENSE2_GPIO=46
MOTOR7_SENSE1_GPIO=30
MOTOR7_SENSE2_GPIO=31
MOTOR8_SENSE1_GPIO=14
MOTOR8_SENSE2_GPIO=15

MOTOR6_PWM_GPIO_NO=27
MOTOR7_PWM_GPIO_NO=35
MOTOR8_PWM_GPIO_NO=117

SYSFS_GPIO_PREFIX=/sys/class/gpio/gpio


MOTOR6_PWM_GPIO=${SYSFS_GPIO_PREFIX}${MOTOR6_PWM_GPIO_NO}/
MOTOR7_PWM_GPIO=${SYSFS_GPIO_PREFIX}${MOTOR7_PWM_GPIO_NO}/
MOTOR8_PWM_GPIO=${SYSFS_GPIO_PREFIX}${MOTOR8_PWM_GPIO_NO}/

MOTOR1_DIR=${SYSFS_GPIO_PREFIX}${MOTOR1_DIR_GPIO}/
MOTOR2_DIR=${SYSFS_GPIO_PREFIX}${MOTOR2_DIR_GPIO}/
MOTOR3_DIR=${SYSFS_GPIO_PREFIX}${MOTOR3_DIR_GPIO}/
MOTOR4_DIR=${SYSFS_GPIO_PREFIX}${MOTOR4_DIR_GPIO}/
MOTOR5_DIR=${SYSFS_GPIO_PREFIX}${MOTOR5_DIR_GPIO}/
MOTOR6_DIR=${SYSFS_GPIO_PREFIX}${MOTOR6_DIR_GPIO}/
MOTOR7_DIR=${SYSFS_GPIO_PREFIX}${MOTOR7_DIR_GPIO}/
MOTOR8_DIR=${SYSFS_GPIO_PREFIX}${MOTOR8_DIR_GPIO}/

MOTOR1_SENSE1=${SYSFS_GPIO_PREFIX}${MOTOR1_SENSE1_GPIO}/
MOTOR1_SENSE2=${SYSFS_GPIO_PREFIX}${MOTOR1_SENSE2_GPIO}/
MOTOR2_SENSE1=${SYSFS_GPIO_PREFIX}${MOTOR2_SENSE1_GPIO}/
MOTOR2_SENSE2=${SYSFS_GPIO_PREFIX}${MOTOR2_SENSE2_GPIO}/
MOTOR3_SENSE1=${SYSFS_GPIO_PREFIX}${MOTOR3_SENSE1_GPIO}/
MOTOR3_SENSE2=${SYSFS_GPIO_PREFIX}${MOTOR3_SENSE2_GPIO}/
MOTOR4_SENSE1=${SYSFS_GPIO_PREFIX}${MOTOR4_SENSE1_GPIO}/
MOTOR4_SENSE2=${SYSFS_GPIO_PREFIX}${MOTOR4_SENSE2_GPIO}/
MOTOR5_SENSE1=${SYSFS_GPIO_PREFIX}${MOTOR5_SENSE1_GPIO}/
MOTOR5_SENSE2=${SYSFS_GPIO_PREFIX}${MOTOR5_SENSE2_GPIO}/
MOTOR6_SENSE1=${SYSFS_GPIO_PREFIX}${MOTOR6_SENSE1_GPIO}/
MOTOR6_SENSE2=${SYSFS_GPIO_PREFIX}${MOTOR6_SENSE2_GPIO}/
MOTOR7_SENSE1=${SYSFS_GPIO_PREFIX}${MOTOR7_SENSE1_GPIO}/
MOTOR7_SENSE2=${SYSFS_GPIO_PREFIX}${MOTOR7_SENSE2_GPIO}/
MOTOR8_SENSE1=${SYSFS_GPIO_PREFIX}${MOTOR8_SENSE1_GPIO}/
MOTOR8_SENSE2=${SYSFS_GPIO_PREFIX}${MOTOR8_SENSE2_GPIO}/

SYSFS_PWM_PREFIX=/sys/class/pwm/

MOTOR1_PWM=/sys/class/pwm/ehrpwm.0:0/
MOTOR2_PWM=/sys/class/pwm/ehrpwm.0:1/
MOTOR3_PWM=/sys/class/pwm/ehrpwm.2:0/
MOTOR4_PWM=/sys/class/pwm/ehrpwm.2:1/
MOTOR5_PWM=/sys/class/pwm/ecap.2/
MOTOR6_PWM=/sys/class/pwm/ecap.0/
MOTOR7_PWM=/sys/class/pwm/ehrpwm.1:0/
MOTOR8_PWM=/sys/class/pwm/ehrpwm.1:1/

